<?=$this->titulo?>
<?=$this->adicionar?>
<table class="TabelaLista">
    <tr>
        <th>#</th>
        <th>T&iacute;tulo</th>
        <th>Tabela</th>
        <th>Módulo</th>
        <th>A&ccedil;&otilde;es</th>
    </tr>
    <? foreach($this->dados as $k => $v): ?>
    <tr>
        <td class="primary_key"><?=$v->id?></td>
        <td><?=$v->titulo?></td>
        <td><?=$v->tabela?></td>
        <td><?=$v->findParentRow('Creator_Model_Modulo','Modulo')->titulo?></td>
        <td class="actions">
            <a href="<?=$this->url(array(
                'module'=>'creator',
                'controller'=>'controlador',
                'action'=>'sincronizar',
                'id'=>$v->id
            ));?>" title="Criar Formulário" class="button frm"></a>
            
            <a href="<?=$this->url(array(
                'module'=>'creator',
                'controller'=>'controlador',
                'action'=>'ver',
                'id'=>$v->id
            ));?>" class="button ver"></a>
            <a href="<?=$this->url(array(
                'module'=>'creator',
                'controller'=>'controlador',
                'action'=>'editar',
                'id'=>$v->id
            ));?>" class="button edt"></a>
            <a href="<?=$this->url(array(
                'module'=>'creator',
                'controller'=>'controlador',
                'action'=>'deletar',
                'id'=>$v->id
            ));?>" class="button del"></a>
        </td>
    </tr>
    <? endforeach; ?>
</table>