Doctrine\Tests\ORM\Mapping\User:
  type: entity
  table: cms_users
  indexes:
    name_index:
      columns: [ name ]
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 50