<?=$this->titulo?>
<?=$this->adicionar?>
<table class="TabelaLista">
    <tr>
        <? foreach($this->colunas as $k => $v): ?>
            <th><?=$k?></th>
        <? endforeach; ?>
        <th>A&ccedil;&otilde;es</th>
    </tr>
    <?

    if($this->dados)
    foreach($this->dados as $dado): ?>
    <tr>
        <?

        $x = 0;
        foreach($this->colunas as $k => $v): ?>
        <td <?=($x == 0)?'class="primary_key"':'';?>><?=$dado->$v?></td>
        <?
        $x++;
        endforeach; ?>
        <td class="actions">
            <a href="<?=$this->url(array(
                'module'=>'creator',
                'controller'=>'controlador',
                'action'=>'ver',
                'id'=>$v->id
            ));?>" class="button ver"></a>
            <a href="<?=$this->url(array(
                'module'=>'creator',
                'controller'=>'controlador',
                'action'=>'editar',
                'id'=>$v->id
            ));?>" class="button edt"></a>
            <a href="<?=$this->url(array(
                'module'=>'creator',
                'controller'=>'controlador',
                'action'=>'deletar',
                'id'=>$v->id
            ));?>" class="button del"></a>
        </td>
    </tr>
    <? endforeach; ?>
</table>