<?=$this->titulo?>
<?=$this->adicionar?>
<table class="TabelaLista">
    <tr>
        <th>#</th>
        <th>T&iacute;tulo</th>
        <th>Tabela</th>
        <th>Controlador</th>
        <th>A&ccedil;&otilde;es</th>
    </tr>
    <? foreach($this->dados as $k => $v): ?>
    <tr>
        <td class="primary_key"><?=$v->id?></td>
        <td><?=$v->titulo?></td>
        <td><?=$v->tabela?></td>
        <td><?=$v->findParentRow('Creator_Model_Controlador','Controlador')->titulo?></td>
        <td class="actions">
            <a href="<?=$this->url(array(
                'module'=>'creator',
                'controller'=>'formulario',
                'action'=>'sincronizar',
                'id'=>$v->id
            ));?>" class="button sync" title="Sincronizar"></a>
            <a href="<?=$this->url(array(
                'module'=>'creator',
                'controller'=>'formulario-campo',
                'action'=>'index',
                'form'=>$v->id
            ));?>" class="button frm" title="Campos do Form"></a>
            <a href="<?=$this->url(array(
                'module'=>'creator',
                'controller'=>'formulario',
                'action'=>'ver',
                'id'=>$v->id
            ));?>" class="button ver" title="Visualizar"></a>
            <a href="<?=$this->url(array(
                'module'=>'creator',
                'controller'=>'formulario',
                'action'=>'editar',
                'id'=>$v->id
            ));?>" class="button edt" title="Editar"></a>
            <a href="<?=$this->url(array(
                'module'=>'creator',
                'controller'=>'controlador',
                'action'=>'deletar',
                'id'=>$v->id
            ));?>" class="button del" title="Deletar"></a>
        </td>
    </tr>
    <? endforeach; ?>
</table>